spring:
  profiles.active: dev
  codec:
    max-in-memory-size: 10MB

# Enable Spring Boot endpoints and set the base path from "/actuator" to "/"
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: info, health, beans, env
    enabled-by-default: true

info:
  name: lob_postcard_service

server:
  port: 8080
  error:
    includeStacktrace: ALWAYS